### ISSUE TITLE
It seems to not be working in chrome 62

### ISSUE THREAD

**Issue by silviapfeiffer** [nusofthq/Media-Recorder-API-Demo#3]
It seems to not be working in chrome 62 - I cannot play back the recording

**Comment by octavn** [comment]
I've played a lot with this demo during the last several days and I had no issues with it on Chrome 62 on both macOS and Windows. 

Are you on Mac? 
Try restarting Chrome, if it starts working let me know.

**Comment by silviapfeiffer** [comment]
Yes, it was Mac and I had to restart the browser. Sigh. Sorry about the noise.

**Comment by octavn** [comment]
No need to be sorry.  It's a known issue with Chrome on Mac where it gets into a state where a restart is required for proper access to the microphone.

It looks like it will be solved in Chrome 63. Google engineers talk in depth about the issue in this recent presentation/video https://youtu.be/PEXnbTyygi4?t=11m44s
